services:
  homepage360:
    build: .
    image: homepage360:latest
    container_name: homepage360
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage360.rule=Host(`votre-domaine.com`)"
      - "traefik.http.routers.homepage360.entrypoints=websecure"
      - "traefik.http.routers.homepage360.tls.certresolver=myresolver"
      - "traefik.http.services.homepage360.loadbalancer.server.port=80"

networks:
  web:
    external: true
